In [15]:
import numpy as np

# Randomly choose number of dimensions (1 to 5)
num_dims = np.random.randint(1, 6)

# For each dimension, choose a random size (between 2 and 5)
shape = tuple(np.random.randint(2, 6) for _ in range(num_dims))

# Create a random array with that shape
array = np.random.rand(*shape)

# Print the array and its shape
print("Array:")
print(array)

Array:
[[[[0.017849   0.77737139 0.91527881]
   [0.53528091 0.86352985 0.18422314]
   [0.07156017 0.47462112 0.32772603]
   [0.14879038 0.15427825 0.1851429 ]]

  [[0.37562741 0.06945289 0.16515164]
   [0.41406872 0.77012294 0.85745008]
   [0.45673143 0.52185111 0.52243676]
   [0.21315547 0.22032172 0.96545787]]]


 [[[0.55708564 0.88880035 0.42735625]
   [0.61046196 0.48732977 0.15603725]
   [0.31582928 0.81583621 0.14859226]
   [0.67598323 0.17164051 0.77502047]]

  [[0.50839359 0.24515339 0.27944329]
   [0.77127608 0.3999734  0.7268236 ]
   [0.30205058 0.35378903 0.62079953]
   [0.04199914 0.85346876 0.12679605]]]


 [[[0.37596203 0.19696327 0.11507997]
   [0.9024678  0.67993297 0.5142056 ]
   [0.07353182 0.97362372 0.02271303]
   [0.15618728 0.36551333 0.42553252]]

  [[0.69112586 0.70193749 0.77129549]
   [0.4753351  0.36338308 0.49769242]
   [0.918229   0.28818344 0.93254529]
   [0.8501816  0.94340708 0.52366644]]]


 [[[0.64930362 0.4343269  0.26555149]
   [0.44386419 0.5031333 

In [16]:
print("\nShape:", array.shape)


Shape: (4, 2, 4, 3)


In [2]:
import numpy as np

def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    # (≈ 1 line of code)
    # v =
    # YOUR CODE STARTS HERE
    v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    
    # YOUR CODE ENDS HERE
    
    return v




In [3]:
import numpy as np

# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

# print(t_image.shape)


print ("image2vector(image) = " + str(image2vector(t_image)))

# image2vector(image2vector)

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [4]:
arr = np.random.rand(3, 2, 5, 1,2, 1)

print(arr)
# print(arr.shape)

[[[[[[0.19215867]
     [0.11184709]]]


   [[[0.37811637]
     [0.79434782]]]


   [[[0.06798064]
     [0.41154643]]]


   [[[0.01728994]
     [0.94205301]]]


   [[[0.00452308]
     [0.00957671]]]]



  [[[[0.69575665]
     [0.72760401]]]


   [[[0.64028551]
     [0.15580839]]]


   [[[0.00222088]
     [0.37700688]]]


   [[[0.29016157]
     [0.32050012]]]


   [[[0.31792152]
     [0.86228224]]]]]




 [[[[[0.65424708]
     [0.21319237]]]


   [[[0.89773515]
     [0.19303853]]]


   [[[0.3517852 ]
     [0.67362948]]]


   [[[0.71271121]
     [0.8234612 ]]]


   [[[0.79285751]
     [0.57238517]]]]



  [[[[0.85305148]
     [0.31640216]]]


   [[[0.33536767]
     [0.51197831]]]


   [[[0.9432072 ]
     [0.59382689]]]


   [[[0.81704088]
     [0.44822442]]]


   [[[0.70785719]
     [0.80990912]]]]]




 [[[[[0.25998943]
     [0.6708621 ]]]


   [[[0.2746856 ]
     [0.70891123]]]


   [[[0.74522067]
     [0.22178618]]]


   [[[0.09069602]
     [0.08515153]]]


   [[[0.85345306]
     [0.33

In [5]:
arr = np.random.rand(10, 1, 5)
arr2 = np.random.rand(1, 8, 5)
result = arr + arr2
result.shape


(10, 8, 5)