In [3]:
import numpy as np

# a is shape (3, 4)
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# b is shape (4, 1)
b = np.array([[100],
              [200],
              [300],
              [400]])

# Loop version
c_loop = np.zeros_like(a)
for i in range(3):
    for j in range(4):
        c_loop[i][j] = a[i][j] + b[j]

# Vectorized version
c_vec = a + b.T   # Transpose b to shape (1, 4), broadcasts across a's rows

print(b)
print(b.T)
print("\n\n")

print("c_loop:\n", c_loop)
print("\nc_vec:\n", c_vec)
print("\nAre they equal?", np.array_equal(c_loop, c_vec))


[[100]
 [200]
 [300]
 [400]]
[[100 200 300 400]]



c_loop:
 [[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]]

c_vec:
 [[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]]

Are they equal? True


C:\Users\Jamie\AppData\Local\Temp\ipykernel_18052\1754149808.py:18: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  c_loop[i][j] = a[i][j] + b[j]
